export interface EnglishSentence {
  en: string
  ko: string
}

export const ENGLISH_SENTENCES: EnglishSentence[] = [
  { en: 'Small steps still move you forward.', ko: '작은 걸음도 앞으로 나아가게 해요.' },
  { en: "Today doesn't have to be perfect, just honest.", ko: '오늘이 완벽할 필요는 없어요, 솔직하기만 하면 돼요.' },
  { en: 'Rest is part of the progress, not a break from it.', ko: '휴식도 성장의 일부예요, 거기서 벗어난 게 아니고요.' },
  { en: 'You are allowed to change your mind.', ko: '마음을 바꿔도 괜찮아요.' },
  { en: "It's okay to take things one day at a time.", ko: '하루하루 천천히 해도 괜찮아요.' },
  { en: 'Your feelings are valid, even the messy ones.', ko: '당신의 감정은 정당해요, 복잡한 감정이라도요.' },
  { en: 'Progress rarely feels as fast as we want it to.', ko: '발전은 우리가 원하는 만큼 빠르게 느껴지지 않아요.' },
  { en: 'Be gentle with yourself today.', ko: '오늘은 스스로에게 다정하게 대해주세요.' },
  { en: 'A good night’s sleep can change your whole outlook.', ko: '숙면 한 번이 하루 전체의 시각을 바꿀 수 있어요.' },
  { en: 'Celebrate the small wins, they add up.', ko: '작은 성취를 축하하세요, 쌓이면 커져요.' },
  { en: 'You don’t have to have it all figured out.', ko: '모든 걸 다 알아낼 필요는 없어요.' },
  { en: 'Curiosity is a great cure for boredom.', ko: '호기심은 지루함을 이기는 좋은 약이에요.' },
  { en: 'Take a deep breath before you react.', ko: '반응하기 전에 깊게 숨을 쉬어보세요.' },
  { en: 'Every habit starts with a single repetition.', ko: '모든 습관은 한 번의 반복에서 시작돼요.' },
  { en: 'Comparison steals the joy of your own pace.', ko: '비교는 당신만의 속도가 주는 기쁨을 빼앗아요.' },
  { en: 'Consistency beats intensity in the long run.', ko: '장기적으로는 꾸준함이 강도를 이깁니다.' },
  { en: 'It’s okay to ask for help.', ko: '도움을 요청해도 괜찮아요.' },
  { en: 'Not every day needs to be productive.', ko: '매일이 생산적일 필요는 없어요.' },
  { en: 'Kindness costs nothing but means everything.', ko: '친절은 돈이 들지 않지만 모든 걸 의미해요.' },
  { en: 'You grow the most outside your comfort zone.', ko: '편안한 영역 밖에서 가장 많이 성장해요.' },
  { en: 'Give yourself credit for showing up today.', ko: '오늘 나타난 것만으로도 스스로를 인정해주세요.' },
  { en: 'A calm mind makes better decisions.', ko: '차분한 마음이 더 나은 결정을 만들어요.' },
  { en: 'Your pace is valid, even if it’s slow.', ko: '느리더라도 당신의 속도는 정당해요.' },
  { en: 'Doing something imperfectly is better than not doing it at all.', ko: '불완전하게라도 하는 게 아예 안 하는 것보다 나아요.' },
  { en: 'You can start again as many times as you need.', ko: '필요한 만큼 몇 번이든 다시 시작해도 돼요.' },
  { en: 'Gratitude turns what you have into enough.', ko: '감사함은 가진 것을 충분한 것으로 만들어줘요.' },
  { en: 'Your worth isn’t measured by your productivity.', ko: '당신의 가치는 생산성으로 측정되지 않아요.' },
  { en: 'Let today be simple.', ko: '오늘은 단순하게 지내도 괜찮아요.' },
  { en: 'A short walk can clear a cluttered mind.', ko: '짧은 산책이 복잡한 머리를 맑게 해줘요.' },
  { en: 'Trust the process, even when it’s slow.', ko: '느리더라도 과정을 믿어보세요.' },
  { en: 'You don’t need permission to rest.', ko: '쉬는 데 허락은 필요 없어요.' },
  { en: 'Focus on direction, not just speed.', ko: '속도보다 방향에 집중하세요.' },
  { en: 'Little rituals make ordinary days feel special.', ko: '작은 루틴이 평범한 하루를 특별하게 만들어요.' },
  { en: 'It’s never too late to try again.', ko: '다시 시도하기에 늦은 때는 없어요.' },
  { en: 'You are more resilient than you think.', ko: '당신은 생각보다 훨씬 단단한 사람이에요.' },
  { en: 'A little sunlight goes a long way.', ko: '햇살을 조금만 쬐어도 큰 도움이 돼요.' },
  { en: 'What you practice, you become.', ko: '연습하는 대로 사람은 그렇게 되어가요.' },
  { en: 'Choose progress over perfection.', ko: '완벽함보다 나아지는 것을 선택하세요.' },
  { en: 'You are exactly where you need to be right now.', ko: '지금 당신은 있어야 할 바로 그 자리에 있어요.' },
  { en: 'Slow down, you’re not behind.', ko: '천천히 가도 돼요, 뒤처진 게 아니에요.' },
  { en: 'A single good habit can change the shape of a day.', ko: '좋은 습관 하나가 하루의 모습을 바꿀 수 있어요.' },
  { en: 'Your energy is precious, spend it wisely.', ko: '당신의 에너지는 소중하니 현명하게 쓰세요.' },
  { en: 'Be proud of how far you’ve already come.', ko: '지금까지 온 만큼을 자랑스러워하세요.' },
  { en: 'Change happens in small, repeated choices.', ko: '변화는 작고 반복되는 선택 속에서 일어나요.' },
  { en: 'Today is a fresh page, write it gently.', ko: '오늘은 새 페이지예요, 부드럽게 채워보세요.' },
  { en: 'Ask yourself what you actually need right now.', ko: '지금 정말 필요한 게 뭔지 스스로에게 물어보세요.' },
  { en: 'Joy can be found in ordinary moments.', ko: '기쁨은 평범한 순간에서도 찾을 수 있어요.' },
  { en: 'You don’t have to earn your rest.', ko: '휴식은 굳이 노력해서 얻어낼 필요가 없어요.' },
  { en: 'Keep going, even slowly.', ko: '느리더라도 계속 나아가세요.' },
  { en: 'One honest sentence in your journal is enough today.', ko: '오늘은 일기에 솔직한 한 문장이면 충분해요.' }
]
